config/routes.rb
#coding: UTF-8
Sdstroi::Application.routes.draw do


  #ComfortableMexicanSofa::Routing.admin(:path => '/admin')

  # .ru to .рф redirect
  constraints(:host => /6400906.ru/) do
    match "/(*path)" => redirect {|params, req|"http://6400906.xn--p1ai/" }
  end

  get '/admin', to: redirect("/cms-admin")
  namespace :comfy do
    put "set_configuration" => "configurations#set"
    resources :advertisement_blocks
    resources :partners do
      put :sort, on: :collection
    end
    resources :main_page_slides do
      collection do
        put :set_slider_time
        put :sort
        put :projects_sort
      end
    end
    resources :news
    resources :projects do
      resources :photos
      resources :slides
      resources :floors
      resources :flats
      resources :flat_images
      resources :houses
      resources :areas do
        resources :layouts do
          member{ post :add_queue }
        end
      end
    end
  end

  resource :root_page
  resources :news

  root to: 'root_page#index'

  match '/news'                     => 'news#index'
  match '/news/filter/:year/'       => 'news#index'
  match '/news/filter/:year/:month' => 'news#index'
  match '/news/:id'                 => 'news#show'


  #TODO fix project routes
  get 'projects'                => 'projects#index'
  get 'projects/all'            => 'projects#index',    scope: :all
  get 'projects/completed'      => 'projects#index',    scope: :completed
  get 'projects/change_buy'     => "projects#change_buy"
  get 'projects/:slug'          => 'projects#show',     as: :project
  get 'projects/:slug/layout'   => 'projects#layout',   as: :project_layout
  get 'projects/:slug/progress' => 'projects#progress', as: :project_progress
  get 'projects/:slug/live'     => 'projects#live',     as: :project_live
  get 'projects/:slug/buy'      => 'projects#buy',      as: :project_buy
  get 'projects/:slug/plan'     => 'projects#plan',     as: :project_plan
  get 'projects/:slug/buy/:area_id/:layout_id'    => 'projects#buy',    as: :project_buy_area_layout
  post 'projects/:slug/send_request' => 'projects#send_request', as: :send_request
  get 'projects/:slug/layout/:area_id/'           => 'projects#layout', as: :project_layout_area
  get 'projects/:slug/layout/:area_id/:layout_id' => 'projects#layout', as: :project_layout_area_layout
  get 'projects/:slug/flats/:flat_id' => 'projects#flats', as: :project_flat

  #ComfortableMexicanSofa::Routing.content(path: '/', sitemap: false)
end

app/views/shared/_advertisement_popup.html.haml
- advertisement = AdvertisementBlock.first
- if advertisement.present? && advertisement.published
  .container
    .adv-popup
      .close-btn 
      .adv-content= advertisement.content.html_safe
      = link_to "Подробнее ›››", advertisement.permalink

  :css
    .adv-popup{
      background: #{advertisement.color};
    }
    .adv-popup:after{
      background: #{advertisement.color};
    }

app/views/shared/_breadcrubms.html.erb
<div class="breadcrubms center960">
  <ul>
    <%= raw get_page_name %>
  </ul>
</div>

<div style="clear: both;"></div>

<hr class="hr-orange hr-breadcrubms">

<script type="text/javascript">
    $('.breadcrubms li a').last().css('color', '#cdcdcd');
</script>

app/views/shared/_comfy_html_head.haml
= stylesheet_link_tag "comfortable_mexican_sofa/admin/bootstrap-fileupload.min"
= stylesheet_link_tag "comfortable_mexican_sofa/admin/bootstrap-lightbox.min"
= stylesheet_link_tag "comfortable_mexican_sofa/admin/style"
= stylesheet_link_tag "comfortable_mexican_sofa/admin/redactor"
= stylesheet_link_tag "comfortable_mexican_sofa/admin/bootstrap-select.min"
= stylesheet_link_tag "comfortable_mexican_sofa/admin/clips"
= stylesheet_link_tag "comfy/bootstrap-colorpicker.min"

= javascript_include_tag "comfortable_mexican_sofa/admin/bootstrap-fileupload.min"
= javascript_include_tag "comfortable_mexican_sofa/admin/jquery-ui-1.10.3.custom.min"
= javascript_include_tag "comfortable_mexican_sofa/admin/bootstrap-lightbox.min"
= javascript_include_tag "comfortable_mexican_sofa/admin/redactor.min"
= javascript_include_tag "comfortable_mexican_sofa/admin/ru"
= javascript_include_tag "comfortable_mexican_sofa/admin/script"
= javascript_include_tag "comfortable_mexican_sofa/admin/bootstrap-select.min"
= javascript_include_tag "comfortable_mexican_sofa/admin/clips"
= javascript_include_tag "comfortable_mexican_sofa/admin/fullscreen"
= javascript_include_tag "comfy/bootstrap-colorpicker.min"
= javascript_include_tag "comfy/bootstrap-wysihtml5.ru-RU"
= javascript_include_tag "site/kinetic-v5.0.1"
= javascript_include_tag "site/miniZoomPan"
= javascript_include_tag "comfy/jquery.form-validator.min"
= javascript_include_tag "site/plan"

= render "comfy/shared/redactor_clips"

:javascript
  $.fn.datetimepicker.dates['en'] = {
    days: #{t("date.day_names")},
    daysShort: #{t("date.abbr_day_names")},
    daysMin: #{t("date.abbr_day_names")},
    months: #{I18n.t("date.standalone_month_names")},
    monthsShort: #{t("date.abbr_month_names").compact},
    today: "Сегодня"
  };
  $(document).ready(function(){
  })
:css
  .form-horizontal .controls {
    margin-left: 170px;
  }

app/views/shared/_comfy_navigation.html.erb
<a href="/comfy/news">Новости</a>
<a href="/comfy/projects">Проекты</a>
<%= link_to "Слайды на главной", comfy_main_page_slides_path%>
<%= link_to "Партнеры ", comfy_partners_path%>
<%= link_to "Рекламный попап", comfy_advertisement_blocks_path%>

app/views/shared/_contacts.html.erb
<div id="contacts">
    <section class="contacts-section">
      <div class="container">
        <div class="sixteen columns">
          <div class="contacts-header">
            <h1 class="contacts-h1">КОНТАКТЫ</h1>
            <hr class="hr-orange hr-contacts-header" />
          </div>
        </div>
      </div>

      <div class="container">
        <div class="eight columns">
          <div class="contacts-header">
            <h2>АДРЕС</h2>
            <hr class="hr-contacts-address" />
            <p class="address-p">
              г. Санкт-Петербург, пл. Карла Фаберже, 8 оф.717 <wbr>
              ст. м. Ладожская (вход со стороны МебельХолла)
            </p>

          </div>
        </div>


        <style>
            .contacts-h1 {
                font-family: "Open Sans";
                font-size: 35px;
                font-weight: 300;
                text-transform: uppercase;
                -webkit-margin-before: 0px;
                margin-bottom: 16px;
            }

            h2 {
                font-family: "Open Sans";
                font-size: 30px;
                font-weight: 400;
                text-transform: uppercase;
                -webkit-margin-before: 0px;
                margin-bottom: 30px;
            }


          .address-p {
              font-family: "Open Sans";
              font-size: 18px;
              line-height: 30px;
              color: #58585a;
          }

          .social-p {
              font-family: "Open Sans";
              font-size: 14px;
              color: black;
              font-weight: bold;
              margin-bottom: 0px;
              margin-top: 15px;
          }

          a {
              color: #fc2121;
          }
          .contacts-section {
              margin-top: 45px;
              margin-bottom: 60px;
          }

          .hr-contacts-header {
              width: 181px;
              margin-bottom: 55px;
              border: 2px solid #fc0101;
          }

          .hr-contacts-adress {
              width: 138px;

          }
          .hr-contacts-phone, .hr-contacts-address {
              width: 138px;
              border-width: 2px;
          }

          .phone-p {
              font-family: "Open Sans";
              font-size: 28px;
              line-height: 30px;
              color: #58585a;

          }
        </style>

    <div class="six columns offset-by-two">
      <div class="contacts-header">
        <h2>ТЕЛЕФОН</h2>
        <hr class="hr-contacts-phone" />
        <p class="phone-p">
          (812) 640 - 09 - 06
        </p>
      </div>
    </div>
  </div>

</section>

<div id="yamap-contacts">
  <a class="yamap-link" href="http://maps.yandex.ru/?ll=30.437694%2C59.934290&spn=0.033903%2C0.009153&z=16&l=map">
    Посмотреть на карте большего масштаба
  </a>
</div>

<style>


  #yamap-contacts {
    width: 100%;
    height: 450px;
  }

  a.yamap-link {
      position: relative;
      top: 440px;
      left: 20px;
      z-index: 10;
      font-size: 14px;
  }

</style>


<script type="text/javascript">
            /* При успешной загрузке API выполняется
               соответствующая функция */
            ymaps.ready(function () {
                    /* Создание экземпляра карты и его привязка к контейнеру с id="YMapsID" */
                    var myMap = new ymaps.Map("yamap-contacts", {
                    // Центр карты
                    center: [59.935021,30.439775],
                    // Коэффициент масштабирования
                    zoom: 16
                    // Тип карты
                    //type: "yandex#satellite"
                    }
                    );

                myMap.controls.add('zoomControl', { left: 5, top: 5 });

                // Создание метки
                var myPlacemark = new ymaps.Placemark(
                        // Координаты метки
                        [59.935021,30.439775],
                        {
                            // Свойства
                            // Текст метки
                            hintContent: 'Союз Делового Строительства. г. Санкт-Петербург, пл. Карла Фаберже, 8 оф.717 ст. м. Ладожская (вход со стороны МебельХолла).'
                        }, {
                            iconImageHref: '/assets/contacts-icon.png', // картинка иконки
                            iconImageSize: [116, 82], // размеры картинки
                            iconImageOffset: [-60, -80] // смещение картинки
                        });

                // Добавление метки на карту
                myMap.geoObjects.add(myPlacemark);

            });
</script>
</div>

app/views/shared/_footer.html.erb
<footer>
  <section class="container footer-section">
    <div class="five columns">
      <p class="footer-sds">© СДС Группа Компаний</p>
      <hr class="hr-orange hr-footer">
      <div class="footer-social">
        <a class="pull-left" href="http://vk.com/sdsstroy"><img src="/assets/vk-soc.png" /></a>
        <a class="pull-left" href="http://www.facebook.com/SDStroy"><img src="/assets/fb-soc.png" /></a>
        <p class="pull-left">Официальные группы</p>
      </div>
    </div>

    <div class="six columns offset-by-one">
      <table class="footer-contacts">
        <tbody>
        <tr>
          <td width="70" align="right"><p><strong>Адресс</strong></p></td>
          <td width="190"><p>г. Санкт-Петербург,<br/>
            пл. Карла Фаберже, 8 оф 717</td>
        </tr>
        <tr>
          <td width="70" align="right"><p><strong>Телефон</strong></p></td>
          <td width="190"><p>(812) 640-09-06</td>
        </tr>
        <tr>
          <td width="70" align="right"><p><strong>E-mail</strong></p></td>
          <td width="190"><a href="mailto:sdscompany@ya.ru"><p>sdscompany@ya.ru</p></a></td>
        </tr>
        </tbody>
      </table>
    </div>

    <div class="four columns">
      <table class="ml-copyright">
        <tbody>
        <tr>
          <td class="logo-td">
            <img src="/assets/ml-logo.png"/>
          </td>
          <td style="vertical-align: top;">
            <p class="footer-copyright" style="margin: -3px 0 0 0; padding: 0;">
              Разработано в студии <br/>дизайна <a href="http://meierlink.ru">«Meier Link»</a>
            </p>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </section>
</footer>

app/views/shared/_header_section.html.erb
<div class="head-class">
  <a class="logo" href="/">
    <%= image_tag "sds-logo.png", alt: "Строительная компания «Союз Долевого Строительства»" %>
  </a>
  <p class="slogan">Малоэтажное строительство <br>
    в Санкт-Петербурге и Ленинградской области
  </p>
  <p class="phone">
    <span class="code">(812)</span>
    640-09-06
  </p>
  <div class="social-links">
    <a class="vk-social" href="http://vk.com/sdsstroy"><img src="/assets/vk-soc-tr.png" /></a>
    <a class="fb-social" href="http://www.facebook.com/SDStroy"><img src="/assets/fb-soc-tr.png" /></a>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="menu">
  <ul>
    <li class="about"><a href="/about">О КОМПАНИИ</a></li>
    <li class="projects"><a href="/projects">ПРОЕКТЫ</a></li>
    <li class="news"><a href="/news">ПРЕСС-ЦЕНТР</a></li>
    <li class="contacts"><a class="last" href="/contacts">КОНТАКТЫ</a></li>
  </ul>
</nav>

app/views/shared/_news.html.haml
- if @single_news
  = render :partial => 'shared/show_news'
- else
  = render :partial => 'shared/news_index'

app/views/shared/_news_index.html.haml
#news_list
  .container
    .eleven.columns
      .news-header
        %h1 ПРЕСС-ЦЕНТР
        %hr{class: 'hr-orange hr-news-header'}
    .two.columns.offset-by-two
      #news_menu
        = render :partial => 'shared/news_menu'
    .news-list
      - @news.each do |comfy_news|
        - if comfy_news.is_published
          %section
            .twelve.columns
              .news-date
                %p= Russian::strftime(comfy_news.date, "%d %B %Y")
                %hr{class: 'hr-news-date'}
            .four.columns
              %a.news-image{href: '/news/' + comfy_news.id.to_s}
                - if comfy_news.logo.present?
                  = image_tag comfy_news.logo.url(:thumb), width: 234, height: 155
            .eight.columns
              .news-content
                %h2= link_to raw(comfy_news.header.gsub("\\n","<br>")), '/news/' + comfy_news.id.to_s
                %p= link_to comfy_news.short_description, '/news/' + comfy_news.id.to_s
    - if @news.count > ::Configuration[:news_per_page].to_i
      .container
        .pagination
          %span Страница:
          = will_paginate @news, class: "pages", next_label: "", previous_label: ""

app/views/shared/_news_menu.html.haml
%p.news-menu-header АРХИВ НОВОСТЕЙ
%hr.hr-news-menu
- Comfy::News.take_year_month_hash.keys.sort.each do |year|
  = link_to year.to_s, '/news/filter/' + year.to_s, class: 'year-menu-link'
  %br
  %ul.news-menu-ul
    - Comfy::News.take_year_month_hash[year].each do |month|
      %li
        = link_to month_num_to_name(month), '/news/filter/' + year.to_s + '/' + month.to_s

app/views/shared/_page_menu.html.erb
<%
menu_pages = if @cms_page.children.published.blank?
  parent = @cms_page.parent
  [parent, parent.children.published.to_a].flatten
else
 [@cms_page, @cms_page.children.published.to_a].flatten
end
%>
<% if menu_pages.present?%>
  <div class='four columns offset-by-one' style="float: right;">
      <ul class="page-menu">
        <% menu_pages.each do |page| %>
          <li class="<%= page.full_path == request.path ? "active" : "" %>"><%= link_to page.label, page.full_path%></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_projects_list.html.erb
<div class="container">
  <div class="sixteen columns">
    <h2 class="project-h2 projects-index-header">ПРОЕКТЫ</h2>
  </div>
</div>

<div class="container">
  <div class="sixteen columns">
    <ul class="project-select">
      <li class="active-project"><a href="">Строящиеся</a></li>
      <li><a href="">Завершенные</a></li>
      <li><a href="">Все</a></li>
    </ul>
  </div>
</div>

<div style="clear: both"></div>

<style>
  ul.project-select {
    list-style: none;
    margin-bottom: 60px;
  }

  ul.project-select li {
      float: left;
      padding: 10px 20px 10px 20px;
      margin-right: 10px;
  }

  ul.project-select li.active-project {
      background-color: #d7240a;
  }


  ul.project-select li a {
    text-decoration: none;
    color: black;
    font-family: "Open Sans";
    font-size: 20px;
    font-weight: 400;
  }

  ul.project-select li.active-project a {
      color: white;
  }


</style>


<div class="project-section">
  <img class="project-image" src="/assets/romanov-project.png" />
  <div class="project-info">
    <div class="infobox info-right">
      <h2 class="project-h2">Клубный дом "Романов"</h2>
      <h3 class="project-h3">Бизнесс-класс</h3>
      <hr class="hr-orange hr-project-info" />
      <p class="project-address">
        Ленинградская область, Всеволожский район поселок Романовка, ул. Дорога жизни, дом 43
      </p>
      <div class="project-icons">
        <img src="/assets/project-icon-1.png" />
        <img src="/assets/project-icon-2.png" />
        <img src="/assets/project-icon-3.png" />
        <img src="/assets/project-icon-4.png" />
        <img src="/assets/project-icon-5.png" />
      </div>
    </div>
  </div>
</div>

<style>
  .projects-index-header {
      margin-bottom: 30px;
  }

  .infobox {
      width: 520px;
  }

  .info-right {
      margin-left: 45px;
      margin-top: 70px;
  }

  h2 {
      font-family: "Open Sans";
      font-size: 38px;
      font-weight: 300;
      color: black;
      text-transform: uppercase;
  }

  h3 {
      font-family: "Open Sans";
      font-size: 26px;
      font-weight: 300;
      color: gray;
      text-transform: uppercase;
  }

  .hr-project-info {
      width: 137px;
      border-width: 2px;
      margin-top: 25px;
  }

  .project-address {
      font-family: "Open Sans";
      font-size: 16px;
      font-weight: 400;
      line-height: 26px;
      color: #6d6d6f;
  }

  .project-icons {
      margin-left: -5px;
      margin-top: 35px;
  }

  .project-icons img {
      margin-right: 10px;
  }

</style>

<div class="project-section">
  <div class="project-info">
    <div class="infobox info-left">
      <h2 class="project-h2">ЖК Румболово</h2>
      <h3 class="project-h3">Бизнесс-класс</h3>
      <hr class="hr-orange hr-project-info" />
      <p class="project-address">
        Ленинградская область, Всеволожский район, г. Всеволожск, район Магнитной станции, участок «Прищегловский»
      </p>



      <div class="project-icons">
        <img src="/assets/project-icon-1.png" />
        <img src="/assets/project-icon-2.png" />
        <img src="/assets/project-icon-3.png" />
        <img src="/assets/project-icon-4.png" />
        <img src="/assets/project-icon-5.png" />
      </div>
    </div>

  </div>
  <img class="project-image" src="/assets/romb-project.png" />
</div>

<div style="clear: both"></div>

<style>
  body {
      overflow-x: hidden;
  }

  .info-left {
      text-align: right;
      float: right;
      margin-top: 75px;
      margin-right: 40px;
  }

  .info-left .hr-project-info {
      margin-left: 377px;
  }

  .project-section {
      width: 1920px;
      height: 470px;
      overflow: hidden;

      position: relative;
      left: -960px;
      margin-left: 50%;
  }

  .project-image {
      float: left;
      width: 960px;
      height: 470px;

      overflow: hidden;
  }

  .project-info {
      float: left;
      width: 960px;
      height: 470px;
      background-color: white;
      overflow: hidden;
  }


</style>

app/views/shared/_show_news.html.haml
#news
  .container
    .eleven.columns
      .news-header
        %h1= raw @single_news.header.gsub("\\n","<br>")
        %hr{class: 'hr-orange hr-news-header'}
    .two.columns.offset-by-two
      #news_menu
        = render :partial => 'shared/news_menu'
    .twelve.columns
      .news-date
        %p= @single_news.date
        %hr{class: 'hr-news-date'}
    .twelve.columns
      .news-content
        = raw @single_news.description

        %p
        %p
          %a{href: '/news'} Вернуться к списку новостей