config/routes.rb
#coding: UTF-8
Sdstroi::Application.routes.draw do


  #ComfortableMexicanSofa::Routing.admin(:path => '/admin')

  # .ru to .рф redirect
  constraints(:host => /6400906.ru/) do
    match "/(*path)" => redirect {|params, req|"http://6400906.xn--p1ai/" }
  end

  get '/admin', to: redirect("/cms-admin")
  namespace :comfy do
    put "set_configuration" => "configurations#set"
    resources :advertisement_blocks
    resources :partners do
      put :sort, on: :collection
    end
    resources :main_page_slides do
      collection do
        put :set_slider_time
        put :sort
        put :projects_sort
      end
    end
    resources :news
    resources :projects do
      resources :photos
      resources :slides
      resources :floors
      resources :flats
      resources :flat_images
      resources :houses
      resources :areas do
        resources :layouts do
          member{ post :add_queue }
        end
      end
    end
  end

  resource :root_page
  resources :news

  root to: 'root_page#index'

  match '/news'                     => 'news#index'
  match '/news/filter/:year/'       => 'news#index'
  match '/news/filter/:year/:month' => 'news#index'
  match '/news/:id'                 => 'news#show'


  #TODO fix project routes
  get 'projects'                => 'projects#index'
  get 'projects/all'            => 'projects#index',    scope: :all
  get 'projects/completed'      => 'projects#index',    scope: :completed
  get 'projects/change_buy'     => "projects#change_buy"
  get 'projects/:slug'          => 'projects#show',     as: :project
  get 'projects/:slug/layout'   => 'projects#layout',   as: :project_layout
  get 'projects/:slug/progress' => 'projects#progress', as: :project_progress
  get 'projects/:slug/live'     => 'projects#live',     as: :project_live
  get 'projects/:slug/buy'      => 'projects#buy',      as: :project_buy
  get 'projects/:slug/plan'     => 'projects#plan',     as: :project_plan
  get 'projects/:slug/buy/:area_id/:layout_id'    => 'projects#buy',    as: :project_buy_area_layout
  post 'projects/:slug/send_request' => 'projects#send_request', as: :send_request
  get 'projects/:slug/layout/:area_id/'           => 'projects#layout', as: :project_layout_area
  get 'projects/:slug/layout/:area_id/:layout_id' => 'projects#layout', as: :project_layout_area_layout
  get 'projects/:slug/flats/:flat_id' => 'projects#flats', as: :project_flat

  #ComfortableMexicanSofa::Routing.content(path: '/', sitemap: false)
end

app/models/comfy.rb
module Comfy
  def self.table_name_prefix
    'comfy_'
  end
end

app/models/comfy/news.rb
class Comfy::News < ActiveRecord::Base
  attr_accessible :date, :header, :short_description, :description, :is_published

  validates :date, presence: true
  validates :header, presence: true
  validates :short_description, length: {maximum: 256}


  attr_accessible :logo
  has_attached_file :logo,
                    :styles => { :thumb => "234x155>" }

  scope :published, where(:is_published => true)


  def self.published_between *attrs
    date = Date.new *attrs.compact.map(&:to_i)
    query_attributes = case attrs.compact.size
                       when 1
                         [date, date.end_of_year]
                       when 2
                         [date, date.end_of_month]
                       end
    if query_attributes
      where("date >= ? AND date <= ?", *query_attributes)
    else
      self
    end.published.order("date DESC")
  end

  def self.take_year_month_hash
    ym_hash = {}
    news = Comfy::News.published
    news.each do |n|
      key = n.date.year
      if ym_hash.has_key?(key)
        ym_hash[key] << n.date.month
        ym_hash[key].sort!
        ym_hash[key].uniq!
      else
        ym_hash[key] = [n.date.month]
      end
    end
    ym_hash
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_protected :id
  before_create :set_default_main_page_slides_position

  mount_uploader :photo, ProjectUploader

  has_many :photos, class_name: ProjectPhoto
  has_many :slides, class_name: ProjectSlide
  has_many :areas,  class_name: ProjectArea
  has_many :houses
  has_many :main_page_slides

  scope :published, where(published: true)
  scope :completed, where(published: true, completed: true)
  scope :underway, where(published: true, completed: false)

  bitmask :objects, as: [:object1, :object2, :object3, :object4, :object5, :object6, :object7]

  validates :slug, :title, :category, :address, :photo, presence: true

  def buyable?
    areas.joins(:layouts).present?
  end

  def layouts
    ProjectLayout.joins(area: :project).where("projects.id = ?", self.id)
  end

  def with_plan?
    houses.present?
  end

  private

  def set_default_main_page_slides_position
    self.main_page_slides_position = Project.maximum(:main_page_slides_position) + 1
  end
end

app/controllers/comfy/advertisement_blocks_controller.rb
class Comfy::AdvertisementBlocksController < CmsAdmin::BaseController
  def index
    @advertisement = AdvertisementBlock.first_or_initialize
  end

  def create
    @advertisement = AdvertisementBlock.first_or_initialize
    @advertisement.update_attributes(params[:advertisement_block])
    @advertisement.save
    redirect_to comfy_advertisement_blocks_path
  end
end

app/controllers/comfy/areas_controller.rb
class Comfy::AreasController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  defaults class_name: 'ProjectArea'

  belongs_to :project
end

app/controllers/comfy/configurations_controller.rb
class Comfy::ConfigurationsController <  CmsAdmin::BaseController

  def set
    params[:configuration].each do |k,v|
      ::Configuration[k] = v
    end
    redirect_to request.referer
  end

end

app/controllers/comfy/flat_images_controller.rb
class Comfy::FlatImagesController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  belongs_to :flat

  def destroy
    super do |format|
      format.html { redirect_to comfy_project_flat_images_url(flat_id: params[:flat_id]) }
    end
  end
  def create
    FlatImage.batch_create(params[:flat_image], params[:flat_id])
    redirect_to comfy_project_flat_images_url(flat_id: params[:flat_id])
  end
  def update
    super do |format|
      format.html { redirect_to comfy_project_flat_images_url(flat_id: params[:flat_id]) }
    end
  end
end

app/controllers/comfy/flats_controller.rb
class Comfy::FlatsController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  belongs_to :floor

  def new
    super do |format|
      format.html
      format.js
    end
  end

  def destroy
    super do |format|
      format.html { redirect_to comfy_project_flats_url(floor_id: params[:floor_id]) }
    end
  end

  def create
    super do |format|
      format.html { redirect_to comfy_project_flats_url(floor_id: params[:floor_id]) }
    end
  end

  def update
    @flat = Flat.find(params[:id])
    if params[:polygon_points]
      @flat.update_attributes(polygon_points: params[:polygon_points].join(","))
    end
    @flat.update_attributes(params[:flat])
    respond_to do |format|
      format.html{redirect_to comfy_project_flats_url(floor_id: @flat.floor_id)}
      format.js{render nothing: true}
    end
  end

end

app/controllers/comfy/floors_controller.rb
class Comfy::FloorsController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  belongs_to :house

  def new
    super do |format|
      format.html
      format.js
    end
  end

  def destroy
    super do |format|
      format.html { redirect_to comfy_project_floors_url(house_id: params[:house_id]) }
    end
  end
  def create
    super do |format|
      format.html { redirect_to comfy_project_floors_url(house_id: params[:house_id])}
    end
  end
  def update
    super do |format|
      format.html { redirect_to comfy_project_floors_url(house_id: params[:house_id]) }
    end
  end

end

app/controllers/comfy/houses_controller.rb
class Comfy::HousesController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  belongs_to :project
end

app/controllers/comfy/layouts_controller.rb
class Comfy::LayoutsController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  defaults class_name: 'ProjectLayout'

  belongs_to :project
  belongs_to :area, class_name: 'ProjectArea'

  def edit
    resource.photos.build
    edit!
  end

  def create
    create! do |success, failure|
      success.html { redirect_to  edit_comfy_project_area_layout_path(@project, @area, @layout) }
    end
  end

  def add_queue
  end
end

app/controllers/comfy/main_page_slides_controller.rb
#coding: utf-8
class Comfy::MainPageSlidesController < CmsAdmin::BaseController

  inherit_resources

  actions :all, except: [:show]

  def edit
    @main_page_slide = MainPageSlide.find(params[:id])
    @project = @main_page_slide.project
  end

  def new
    @project = Project.find(params[:project_id])
    @main_page_slide = @project.main_page_slides.new
  end

  def index
    @projects = Project.order(:main_page_slides_position)
  end

  def destroy
    @main_page_slide = MainPageSlide.find(params[:id])
    @main_page_slide.destroy
  end

  def sort
    params[:main_page_slide].each_with_index do |id, position|
      MainPageSlide.find(id).update_attributes!(position: position, project_id: params[:project_id])
    end
    render nothing: true
  end

  def projects_sort
    params[:project].each_with_index do |id, position|
      Project.find(id).update_attributes!(main_page_slides_position: position)
    end
    render nothing: true
  end

end

app/controllers/comfy/news_controller.rb
#coding: UTF-8
class Comfy::NewsController < CmsAdmin::BaseController
  # GET /comfy/news
  # GET /comfy/news.json

  def index
    @comfy_news = Comfy::News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comfy_news }
    end
  end

  # GET /comfy/news/1
  # GET /comfy/news/1.json
  def show
    @comfy_news = Comfy::News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comfy_news }
    end
  end

  # GET /comfy/news/new
  # GET /comfy/news/new.json
  def new
    @comfy_news = Comfy::News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comfy_news }
    end
  end

  # GET /comfy/news/1/edit
  def edit
    @comfy_news = Comfy::News.find(params[:id])
  end

  # POST /comfy/news
  # POST /comfy/news.json
  def create
    @comfy_news = Comfy::News.new(params[:comfy_news])

    respond_to do |format|
      if @comfy_news.save
        format.html { redirect_to @comfy_news, notice: 'Новость была успешно создана!' }
        format.json { render json: @comfy_news, status: :created, location: @comfy_news }
      else
        format.html { render action: "new" }
        format.json { render json: @comfy_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comfy/news/1
  # PUT /comfy/news/1.json
  def update
    @comfy_news = Comfy::News.find(params[:id])

    respond_to do |format|
      if @comfy_news.update_attributes(params[:comfy_news])
        format.html { redirect_to @comfy_news, notice: 'Новость была успешно обновлена!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comfy_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comfy/news/1
  # DELETE /comfy/news/1.json
  def destroy
    @comfy_news = Comfy::News.find(params[:id])
    @comfy_news.destroy

    respond_to do |format|
      format.html { redirect_to comfy_news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comfy/partners_controller.rb
# coding: UTF-8
class Comfy::PartnersController < CmsAdmin::BaseController
  def index
    @partners = Partner.all
  end

  def new
    @partner = Partner.new
  end

  def edit
    @partner = Partner.find(params[:id])
  end

  def sort
    ids = params[:partner].map(&:to_i)
    Partner.where(id: ids).each do |partner|
      partner.update_attribute(:position, ids.index(partner.id))
    end
    render nothing: true
  end

  def update
    @partner = Partner.find(params[:id])
    if @partner.update_attributes(params[:partner])
      redirect_to comfy_partners_path, notice: "Партнер #{@partner.name} успешно изменен!"
    else
      render :edit
    end
  end

  def create
    @partner = Partner.new(params[:partner])
    if @partner.save
      redirect_to comfy_partners_path, notice: "Партнер успешно добавлен!"
    else
      render :new
    end
  end

  def destroy
    Partner.destroy(params[:id])
    redirect_to comfy_partners_path, notice: "Партнер успешно удален!"
  end
end

app/controllers/comfy/photos_controller.rb
class Comfy::PhotosController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  defaults class_name: 'ProjectPhoto'

  belongs_to :project
end

app/controllers/comfy/projects_controller.rb
class Comfy::ProjectsController < CmsAdmin::BaseController
  inherit_resources
end

app/controllers/comfy/slides_controller.rb
class Comfy::SlidesController < CmsAdmin::BaseController
  inherit_resources

  actions :all, except: [:show]

  defaults class_name: 'ProjectSlide'

  belongs_to :project

  def create
    @project = Project.find(params[:project_id])
    params[:project_slide][:file].each do |file|
      @project.slides.create!(file: file, date: params[:project_slide][:date])
    end
    redirect_to comfy_project_slides_path
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, except: [:index, :change_buy]

  def index
    @collection = case params[:scope]
                    when :all
                      Project.published
                    when :completed
                      Project.completed
                    else
                      Project.underway
                  end
  end

  def show
  end

  def live
  end

  def change_buy
    @project = Project.find(params[:id])
    @request = Request.new
    @area   = (@project.areas.find(params[:area_id]) rescue @project.areas.first)
    @layout = (@area.layouts.find(params[:layout_id]) rescue @area.layouts.first)
  end

  def send_request
    @request = Request.new(params[:request])
    if @request.valid?
      Mailer.request_email(@request).deliver
    end
  end

  def buy
    @request = Request.new
    if @project.buyable?
      @area   = params[:area_id] ? @project.areas.find(params[:area_id]) : @project.areas.first
      @layout = params[:layout_id] ? @area.layouts.find(params[:layout_id]) : @area.layouts.first
    end
  end

  def layout
    @area = params[:area_id].present? ? @project.areas.find(params[:area_id]) : @project.areas.first
    if @area
      @layout = params[:layout_id].present? ? @area.layouts.find(params[:layout_id]) : @area.layouts.first
    end
    @areas  = @project.areas.select { |r| r.layouts.count > 0 }
  end

  def progress
  end

  def plan
    if params[:house_id] || !params[:floor_id]
      @houses = @project.houses
      @current_house = @project.houses.find_by_id(params[:house_id]) || @houses.first
      
      @floors = @current_house.floors.entire
      @current_floor = @floors.find_by_id(params[:floor_id]) || @floors.first
    else
      @current_floor = Floor.find(params[:floor_id])
      @current_house = @current_floor.house
      @floors = @current_house.floors.entire
    end
  end

  def flats
    @flat = Flat.find(params[:flat_id])
  end

  private
  def find_project
    @project = Project.find_by_slug! params[:slug]
  end
end

app/helpers/comfy/advertisement_blocks_helper.rb
module Comfy::AdvertisementBlocksHelper
end

app/helpers/comfy/configurations_helper.rb
module Comfy::ConfigurationsHelper
end

app/views/comfy/projects/_form.html.haml
:css
  .redactor_.redactor_editor{
    min-height: 100px !important;
  }
= form_for(resource, url: resource.new_record? ? collection_url : resource_url(resource),
                     html: { method: (resource.new_record? ? "post" : "put"),
                             class: "formatted form-horizontal"}) do |f|
  - if resource.errors.any?
    .alert
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      %strong Внимание!
      %br
      = raw resource.errors.full_messages.join("<br>")
  .control-group
    = f.label :title, "Заголовок", class: "control-label"
    .controls
      %div
        = f.text_field :title

  .control-group
    = f.label :slug, "Ссылка", class: "control-label"
    .controls
      %div
        = f.text_field :slug
  .control-group
    = f.label :category, "Тип проекта", class: "control-label"
    .controls
      %div
        = f.text_field :category
  .control-group
    = f.label :address, "Адрес", class: "control-label"
    .controls
      %div
        = f.text_area :address, rows: 3, style:"height:auto;"
      %p.help-block Для разделения текста на строки используйте "\n"
  .control-group
    = f.label :photo, "Фото для списка проектов", class: "control-label"
    .controls
      %div
        .fileupload.fileupload-new{"data-provides" => "fileupload"}
          %span.btn.btn-file
            %span.fileupload-new Загрузить изображение
            %span.fileupload-exists Изменить изображение
            = f.file_field :photo
          %span.fileupload-preview
          %a.close.fileupload-exists{"data-dismiss" => "fileupload", :href => "#", :style => "float: none"} ×

  .control-group
    = f.label :description, "Краткое описание", class: "control-label"
    .controls
      %div
        = f.text_area :description, rows: 3, style:"height:auto;"
  .control-group
    = f.label :content, "Подробное описание", class: "control-label"
    .controls
      %div
        = f.text_area :content, :"data-rich-text" => "true", rows: 6, style:"height:auto;"
  .control-group
    = f.label :location, "Расположение", class: "control-label"
    .controls
      %div
        = f.text_area :location, rows: 3, style:"height:auto;"
  .control-group
    = f.label :location_content, "Расположение подробно", class: "control-label"
    .controls
      %div
        = f.text_area :location_content, :"data-rich-text" => "true", rows: 6, style:"height:auto;"
  .control-group
    = f.label "Координаты", class: "control-label"
    .controls
      .span3{style:"margin:0"}
        = f.text_field :lat
      .span3
        = f.text_field :lng
  .control-group
    = f.label :layout, "Текст для страницы планировок", class: "control-label"
    .controls
      %div
        = f.text_area :layout, rows: 3, style:"height:60px;", :"data-rich-text" => "true"
  .control-group
    = f.label :embed_stream, "Ссылка встроенной трансляции", class: "control-label"
    .controls
      %div
        = f.text_field :embed_stream
  .control-group
    = f.label "Инфраструктура", class: "control-label"
    .controls
      %div
        - Project.values_for_objects.each do |o|
          = check_box_tag "project[objects][]", o, resource.objects?(o)
          = t(o, scope: 'objects')
          %br
  .control-group
    = f.label :completed, "Достроен?", class: "control-label"
    .controls
      %div
        = f.check_box :completed
  .control-group
    = f.label :published, "Опубликовать?", class: "control-label"
    .controls
      %div
        = f.check_box :published
  .form-actions
    = f.submit 'Сохранить', class: 'btn'

app/views/comfy/projects/edit.html.haml
.page-header
  %h2 Редактирование проекта

= render 'form'


= link_to 'Показать', resource_path
\|
= link_to 'Вернуться назад', collection_path

app/views/comfy/projects/index.html.haml
.page-header
  = link_to 'Создать проект', new_resource_path, class: 'btn btn-primary pull-right'
  %h2 Список проектов

%table.table.table-striped.table-bordered
  %thead
    %th Проект
    %th{style: "text-align:center;"} Достроен?
    %th{style: "text-align:center;"} Опубликован?
    %th
  %tbody
    - collection.each do |resource|
      %tr
        %td= resource.title
        %td{style: "text-align:center;"}
          - if resource.completed
            %span.label.label-success{style:"padding: 5px;"}
              %i.icon-ok
          - else
            %span.label.label-important{style:"padding: 5px;"}
              %i.icon-remove
        %td{style: "text-align:center;"}
          - if resource.published?
            %span.label.label-success{style:"padding: 5px;"}
              %i.icon-ok
          - else
            %span.label.label-important{style:"padding: 5px;"}
              %i.icon-remove

        %td{style: "text-align:center;"}
          .btn-group
            = link_to comfy_project_photos_path(resource), class: "btn btn-small", title: "Фото" do
              %i.icon-large.icon-camera
            = link_to comfy_project_slides_path(resource), class: "btn btn-small", title: "Слайды процесса" do
              %i.icon-large.icon-film
            = link_to comfy_project_areas_path(resource), class: "btn btn-small", title: "Квартиры" do
              %i.icon-large.icon-home
            = link_to comfy_project_houses_path(resource), class: "btn btn-small", title: "Дома" do
              %i.icon-large.icon-align-justify
          .btn-group
            = link_to resource_path(resource), class: "btn btn-small", title: "Показать" do
              %i.icon-large.icon-eye-open
            = link_to edit_resource_path(resource), class: "btn btn-small", title: "Редактировать" do
              %i.icon-large.icon-edit
            = link_to resource_path(resource), class: "btn btn-small btn-danger", :method => :delete, :data => { :confirm => 'Вы уверены?' }, title: "Удалить" do
              %i.icon-large.icon-trash

app/views/comfy/projects/new.html.haml
.page-header
  %h2 Создание проекта

= render 'form'

= link_to 'Вернуться назад', collection_path

app/views/comfy/projects/show.html.haml
= javascript_include_tag "http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU"
.page-header
  %h2= resource.title

.well.well-large
  %div
    %label
      %b Заголовок:
    %p= resource.title
  %div
    %label
      %b Адрес:
    %p= raw resource.address.gsub("\\n","<br>")
  %div
    %label
      %b Тип проекта:
    %p= resource.category
  %div
    %label
      %b Краткое описание:
    %p= resource.description
  %div
    - if resource.completed
      %p.label.label-success
        %i.icon-ok
        Достроен
    - else
      %p.label.label-important
        %i.icon-remove
        Не достроен
  %div
    - if resource.published
      %p.label.label-success
        %i.icon-ok
        Опубликован
    - else
      %p.label.label-important
        %i.icon-remove
        Не опубликован
  %div
    %label
      %b Карта
    #yamap{style: "margin-top: 20px;width: 100%;height: 400px;position: relative;"}
    :javascript
      ymaps.ready(function () {
        var myMap = new ymaps.Map("yamap", {
          center: [#{resource.lat}, #{resource.lng}],
          zoom: 15
        }
      );

      myMap.controls.add('zoomControl', { left: 5, top: 5 });

      var myPlacemark2 = new ymaps.Placemark(
        [#{resource.lat}, #{resource.lng}],
        {
            hintContent: '<%= @project.title %>'
        }, {
            iconImageHref: '/assets/baloon.png',
            iconImageSize: [96, 101],
            iconImageOffset: [-60, -95]
        });
        myMap.geoObjects.add(myPlacemark2);
      });


= link_to 'Редактировать', edit_resource_path(resource)
\|
= link_to 'Вернуться назад', collection_path