config/routes.rb
#coding: UTF-8
Sdstroi::Application.routes.draw do


  #ComfortableMexicanSofa::Routing.admin(:path => '/admin')

  # .ru to .рф redirect
  constraints(:host => /6400906.ru/) do
    match "/(*path)" => redirect {|params, req|"http://6400906.xn--p1ai/" }
  end

  get '/admin', to: redirect("/cms-admin")
  namespace :comfy do
    put "set_configuration" => "configurations#set"
    resources :advertisement_blocks
    resources :partners do
      put :sort, on: :collection
    end
    resources :main_page_slides do
      collection do
        put :set_slider_time
        put :sort
        put :projects_sort
      end
    end
    resources :news
    resources :projects do
      resources :photos
      resources :slides
      resources :floors
      resources :flats
      resources :flat_images
      resources :houses
      resources :areas do
        resources :layouts do
          member{ post :add_queue }
        end
      end
    end
  end

  resource :root_page
  resources :news

  root to: 'root_page#index'

  match '/news'                     => 'news#index'
  match '/news/filter/:year/'       => 'news#index'
  match '/news/filter/:year/:month' => 'news#index'
  match '/news/:id'                 => 'news#show'


  #TODO fix project routes
  get 'projects'                => 'projects#index'
  get 'projects/all'            => 'projects#index',    scope: :all
  get 'projects/completed'      => 'projects#index',    scope: :completed
  get 'projects/change_buy'     => "projects#change_buy"
  get 'projects/:slug'          => 'projects#show',     as: :project
  get 'projects/:slug/layout'   => 'projects#layout',   as: :project_layout
  get 'projects/:slug/progress' => 'projects#progress', as: :project_progress
  get 'projects/:slug/live'     => 'projects#live',     as: :project_live
  get 'projects/:slug/buy'      => 'projects#buy',      as: :project_buy
  get 'projects/:slug/plan'     => 'projects#plan',     as: :project_plan
  get 'projects/:slug/buy/:area_id/:layout_id'    => 'projects#buy',    as: :project_buy_area_layout
  post 'projects/:slug/send_request' => 'projects#send_request', as: :send_request
  get 'projects/:slug/layout/:area_id/'           => 'projects#layout', as: :project_layout_area
  get 'projects/:slug/layout/:area_id/:layout_id' => 'projects#layout', as: :project_layout_area_layout
  get 'projects/:slug/flats/:flat_id' => 'projects#flats', as: :project_flat

  #ComfortableMexicanSofa::Routing.content(path: '/', sitemap: false)
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_protected :id
  before_create :set_default_main_page_slides_position

  mount_uploader :photo, ProjectUploader

  has_many :photos, class_name: ProjectPhoto
  has_many :slides, class_name: ProjectSlide
  has_many :areas,  class_name: ProjectArea
  has_many :houses
  has_many :main_page_slides

  scope :published, where(published: true)
  scope :completed, where(published: true, completed: true)
  scope :underway, where(published: true, completed: false)

  bitmask :objects, as: [:object1, :object2, :object3, :object4, :object5, :object6, :object7]

  validates :slug, :title, :category, :address, :photo, presence: true

  def buyable?
    areas.joins(:layouts).present?
  end

  def layouts
    ProjectLayout.joins(area: :project).where("projects.id = ?", self.id)
  end

  def with_plan?
    houses.present?
  end

  private

  def set_default_main_page_slides_position
    self.main_page_slides_position = Project.maximum(:main_page_slides_position) + 1
  end
end

app/controllers/comfy/projects_controller.rb
class Comfy::ProjectsController < CmsAdmin::BaseController
  inherit_resources
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, except: [:index, :change_buy]

  def index
    @collection = case params[:scope]
                    when :all
                      Project.published
                    when :completed
                      Project.completed
                    else
                      Project.underway
                  end
  end

  def show
  end

  def live
  end

  def change_buy
    @project = Project.find(params[:id])
    @request = Request.new
    @area   = (@project.areas.find(params[:area_id]) rescue @project.areas.first)
    @layout = (@area.layouts.find(params[:layout_id]) rescue @area.layouts.first)
  end

  def send_request
    @request = Request.new(params[:request])
    if @request.valid?
      Mailer.request_email(@request).deliver
    end
  end

  def buy
    @request = Request.new
    if @project.buyable?
      @area   = params[:area_id] ? @project.areas.find(params[:area_id]) : @project.areas.first
      @layout = params[:layout_id] ? @area.layouts.find(params[:layout_id]) : @area.layouts.first
    end
  end

  def layout
    @area = params[:area_id].present? ? @project.areas.find(params[:area_id]) : @project.areas.first
    if @area
      @layout = params[:layout_id].present? ? @area.layouts.find(params[:layout_id]) : @area.layouts.first
    end
    @areas  = @project.areas.select { |r| r.layouts.count > 0 }
  end

  def progress
  end

  def plan
    if params[:house_id] || !params[:floor_id]
      @houses = @project.houses
      @current_house = @project.houses.find_by_id(params[:house_id]) || @houses.first
      
      @floors = @current_house.floors.entire
      @current_floor = @floors.find_by_id(params[:floor_id]) || @floors.first
    else
      @current_floor = Floor.find(params[:floor_id])
      @current_house = @current_floor.house
      @floors = @current_house.floors.entire
    end
  end

  def flats
    @flat = Flat.find(params[:flat_id])
  end

  private
  def find_project
    @project = Project.find_by_slug! params[:slug]
  end
end

app/views/projects/_area_view.html.erb
<div id="<%= dom_id area %>" class="project-area">
  <%= link_to project_layout_area_path(@project.slug, area.id), remote: true, class: ('selected' if area.id == @area.id) do %>
    <div class="project-area-name"><%= area.name %> м²</div>
    <%=  image_tag area.photo.url(:thumb) %>
    <div class="project-area-amount">В наличии <b><%= area.amount %></b>  <%= Russian::pluralize(area.amount, 'квартира', 'квартиры', 'квартир') %></div>
  <% end %>
</div>

app/views/projects/_area_view_buy.haml
%section.description-section
  = hidden_field_tag "request[layout_id]", @layout.id, id: "layout_id"
  .container
    .eleven.columns
      %ul.project-layouts
        - if @area.layouts.size > 1
          - @area.layouts.each do |layout|
            %li{class: ('selected' if layout.eql?(@layout))}= link_to layout.name,
                project_buy_area_layout_path(@project.slug, @area.id, layout.id), remote: true
      - if @layout.photos.first.present?
        %img.project-layout-photo{src: @layout.photos.first.file.url(:photo)}/
    .five.columns.project-layout-description
      %h2= raw @layout.title.gsub("\\n", "")
      %hr.hr-orange.hr-object-description/
      = raw @layout.content
      %hr.hr-silver{style: "margin:10px 0"}/
      #prices
        - @layout.queues.each do |queue|
          .project-layout-price{id: dom_id(queue)}
            %span.currency= number_to_currency queue.price, unit: "руб.", separator: ",", precision: 0
      %hr.hr-silver{style: "margin:10px 0"}/

      .project-layout-amount
        = Russian::pluralize(@layout.amount.to_i, 'Осталась', 'Осталось', 'Осталось')
        в наличии
        %b
          = @layout.amount.to_i
          = Russian::pluralize(@layout.amount.to_i, 'квартира', 'квартиры', 'квартир')

app/views/projects/_objects_menu.html.erb
<ul class="objects-menu">
  <li>
    <%= link_to "Описание объекта", project_path(@project.slug) %>
  </li>
  <li>
    <%= link_to "Цены и планировки квартир", project_layout_path(@project.slug) %>
  </li>
  <% unless @project.completed? %>
    <li>
      <%= link_to "Ход строительства", project_progress_path(@project.slug) %>
    </li>
  <% end %>
  <!--<li><a href="">Виртуальный тур</a></li>-->
  <li>
    <%= link_to "Купить квартиру", project_buy_path(@project.slug) %>
  </li>
  <% if @project.with_plan? %>
    <li>
      <%= link_to "Поэтажный план", project_plan_path(@project.slug) %>
    </li>
  <% end %>
</ul>
<script>
  $(".objects-menu li a[href='" + location.pathname + "']").closest("li").addClass("active")
</script>

app/views/projects/_project_form.haml
- if @project.buyable?
  = form_for @request, url: send_request_path(@project.slug), remote: true, html: { id: 'form_buy' } do |f|
    .container.projects
      .row
        .sixteen.columns
          %p
            Для того, чтобы приобрести квартиру - оставьте свои контактные данные.
            %br
            Наши менеджеры свяжутся с вами в ближайшее время.
      .row
        .eight.columns
          %label Интересующий жилищный комплекс
          .styled-select
            = f.select :project_id, options_from_collection_for_select(Project.published.all, :id, :title, @project.id)
    .row.bg-gray.projects
      .columns
        .content
          %label Площадь квартиры:
          - @project.areas.each do |area|
            .radio.ajax
              = f.radio_button :area_id, area.id, checked: @area == area
              = f.label "area_id_#{area.id}", "#{area.name} м²"
    .container.projects.objects
      .row
        = render "area_view_buy"
      - if @layout.queues.size > 1
        .row
          .eight.columns
            .wrapper{style: "position: absolute;left: 310px;margin-top: -5px;"}
              .popup
                %p Цена может меняться в зависимости от очереди.
            %label Выберите очередь строительства
            .styled-select
              = f.select :queue_id, options_for_select( @layout.queues.map{|q| ["#{q.position} очередь", q.id]})
  
      .row
        .eight.columns
          %label.radios Вид оплаты:
          .red.radio
            = f.radio_button :payment, 'cash', checked: true
            = f.label :payment_cash, "Наличные"
          .red.radio
            = f.radio_button :payment, 'credit'
            = f.label :payment_credit, "Ипотека"
      .row
        .eight.columns
          %label
            Как к вам обращаться:
            = f.text_field :name, placeholder: 'Любимый покупатель'
      .row
        .eight.columns
          %label
            Как с вами связаться:
            = f.text_field :email, placeholder: 'E-mail или номер телефона'
      .row
        .eight.columns
          = submit_tag 'Отправить заявку на покупку'
- else
  .container.projects
    .row
      %h3 Раздел находится в разработке.

app/views/projects/_side_menu.html.erb
<div class="four columns offset-by-one">
  <div class="project-address">
    <p><%= raw @project.address.gsub("\\n","<br>") %></p>
    <p><a href="#map">посмотреть на карте</a></p>
  </div>

  <%= render "objects_menu" %>
</div>

app/views/projects/buy.js.erb
$("#form_buy").replaceWith("<%= j render("project_form") %>")
$(".popup").popup()
id = $("#request_queue_id").val()
$("#layout_queue_" + id).show()

app/views/projects/change_buy.js.erb
$("#form_buy").replaceWith("<%= j render("project_form") %>");
$(".popup").popup();
id = $("#request_queue_id").val()
$("#layout_queue_" + id).show()

app/views/projects/flats.html.erb
<%
    active_menu_class('projects')
page_title @project.title
%>
<div class="breadcrubms center960">
  <ul>
    <li><a href="/">Главная</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="/projects">Проекты</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="<%= project_path(@project.slug) %>"><%= @project.title %></a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li style="color: rgb(205, 205, 205);">
      <%= link_to "Поэтажный план", project_plan_path(@project.slug) %>
    </li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li style="color: rgb(205, 205, 205);">Фотографии квартиры</li>
    <li></li>
  </ul>
</div>

<div style="clear: both;"></div>
<hr class="hr-orange hr-breadcrubms">

<div class="objects">
  <section>
    <div class="container">
      <div class="columns">
        <h1>Квартира №<%= @flat.number %></h1>
        <% if @flat.description.present? %>
          <hr class="hr-orange hr-objects-short" style="width: 260px;">
          <p class="desc-p">
            <%= raw @flat.description %>
          </p>
        <% end %>
      </div>
    </div>
  </section>

  <% if @flat.flat_images.present? %>
    <section class="projects-slider progress">
      <div class="project-slide" style="height: 860px;">
        <div class="slide-arrows">
          <a class="right-arrow disabled" style="display: block;">
            <div class="tooltip"></div>
          </a>

          <a class="left-arrow" style="display: block;">
            <div class="tooltip"></div>
          </a>
        </div>
        <% if @flat.flat_images.present? %>
          <%= image_tag "ajax-loader.gif", class: "ajax-loader" %>
        <% end %>
        <div id="featured" class="backstretch-container"></div>
        <div class="container">
          <div class="slide-container">
            <div id="slider"></div>
          </div>
        </div>
      </div>
      <div class="slider-thumbs center960">
        <% @flat.flat_images.each_with_index do |photo, n| %>
          <image-data src=<%= photo.image.url %> class="thumb" data-day="<%= photo.data_day %>" alt="<%= l(photo.date.to_date, format: :short).mb_chars.capitalize.to_s %>"></image-data>
        <% end %>
      </div>

    </section>
    <script type="text/javascript">
      <% if @flat.flat_images.present? %>
        $('.backstretch-container').backstretch("<%= @flat.flat_images.last.image.url %>");
      <% end %>

      $('.thumb').click(function() {
          $('.thumb').removeClass('active-thumb');
          $(this).addClass('active-thumb');
          $('.backstretch-container').backstretch($(this).context.src, {fade: 0});
          });

          var tooltip = $('<div id="tooltip" class="tooltip"><div></div></div>').hide();
          tooltip.find('div').text($('.active-thumb').attr('alt'));
          $("#slider").slider({
          min: 0,
          max: <%= @flat.flat_images.size %> - 1,
          value: <%= @flat.flat_images.size %> - 1,
          animate: true,
          range: "min"
          }).find(".ui-slider-handle").append(tooltip).hover(function () {
            tooltip.show()
            }, function () {
            tooltip.hide()
            });
</script>
    <% else %>
      <div class="container row">
        <h3>Пока здесь нет фотографий</h3>
      </div>
    <% end %>
    <style>
      #featured {
        background: #ffffff url('/assets/ajax-loader.gif') no-repeat center center;
        overflow : hidden;
        z-index : -100;
      }
    </style>

</div>

app/views/projects/index.html.erb
<%
    active_menu_class('projects')
    page_title 'Проекты'
%>

<div class="breadcrubms center960">
  <ul>
    <li><a href="/">Главная</a></li><li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li><li><a href="/projects" style="color: rgb(205, 205, 205);">Проекты</a></li><li>
  </li></ul>
</div>

<div style="clear: both;"></div>

<hr class="hr-orange hr-breadcrubms">

<script type="text/javascript">
    $('.breadcrubms li a').last().css('color', '#cdcdcd');
</script>

<div class="container">
  <div class="sixteen columns">
    <h2 class="project-h2 projects-index-header">ПРОЕКТЫ</h2>
  </div>
</div>

<div class="container">
  <div class="sixteen columns">
    <ul class="project-select">
      <%- if Project.published.underway.present? %>
      <li class="<%= 'active-project' if params[:scope].nil? %>"><a href="<%= projects_path %>">Строящиеся</a></li>
      <%- end %>
      <%- if Project.published.completed.present? %>
      <li class="<%= 'active-project' if params[:scope] == :completed %>"><a href="<%= projects_completed_path %>">Завершенные</a></li>
      <%- end %>
      <%- if Project.published.completed.present? && Project.published.underway.present? %>
      <li class="<%= 'active-project' if params[:scope] == :all %>"><a href="<%= projects_all_path %>">Все</a></li>
      <%- end %>
    </ul>
  </div>
</div>

<div style="clear: both"></div>

<style>
  ul.project-select {
    list-style: none;
    margin-bottom: 60px;
  }

  ul.project-select li {
      float: left;
      padding: 10px 20px 10px 20px;
      margin-right: 10px;
  }

  ul.project-select li.active-project {
      background-color: #d7240a;
  }

  ul.project-select li a {
    text-decoration: none;
    color: black;
    font-family: "Open Sans";
    font-size: 20px;
    font-weight: 400;
  }

  ul.project-select li.active-project a {
      color: white;
  }
</style>


<% @collection.each do |project| %>
  <% align_info = cycle('right', 'left', name: :align_info) %>
  <% align_image = cycle('left', 'right', name: :align_image) %>
  <div class="project-section">
    <div class="project-image center-cropped image-align-<%= align_image %>"
      onclick="window.location = '<%= project_path(project.slug) %>'" style="cursor:pointer;background-image: url('<%= project.photo.url(:normal) %>');">
    </div>

    <div class="project-info">
      <div class="infobox info-<%= align_info %>">
        <a href="<%= project_path(project.slug) %>"><h2 class="project-h2"><%= project.title %></h2></a>

        <h3 class="project-h3"><%= project.category %></h3>
        <hr class="hr-orange hr-project-info"/>
        <p class="project-address"><%= project.address.gsub("\\n", "") %></p>
        <p class="project-link-map"><a href="<%= project_path(project.slug, anchor: 'map') %>">Посмотреть на карте</a></p>

        <div class="project-icons">
          <a class="icon-project-info" title="Описание объекта" href="<%= project_path(project.slug) %>"></a>
          <a class="icon-project-layout" title="Цены и планировки квартир" href="<%= project_layout_path(project.slug) %>"></a>

          <%- unless project.completed? %>
            <a class="icon-project-progress" title="Ход строительства" href="<%= project_progress_path(project.slug) %>"></a>
            <%- if project.live.present? %>
              <a class="icon-project-live" title="Виртуальный тур" href="<%= project_live_path(project.slug) %>"></a>
            <%- end %>
          <%- end %>

          <a class="icon-project-buy" title="Купить квартиру" href="<%= project_buy_path(project.slug) %>"></a>
        </div>
      </div>
    </div>
  </div>
<% end %>


<style>
  .image-align-left{
    float:left;
    background-position: center right;
  }
  .image-align-right{
    float:right;
    background-position: center left;
  }
  .projects-index-header {
      margin-top: 21px;
      margin-bottom: 30px;
  }

  .infobox {
      width: 520px;
  }

  .infobox a {
      text-decoration: none;
  }

  .info-right {
      margin-left: 45px;
      margin-top: 70px;
  }

  h2 {
      font-family: "Open Sans";
      font-size: 38px;
      font-weight: 300;
      color: black;
      text-transform: uppercase;
  }

  h3 {
      font-family: "Open Sans";
      font-size: 26px;
      font-weight: 300;
      color: gray;
      text-transform: uppercase;
  }

  .hr-project-info {
      width: 137px;
      border-width: 2px;
      margin-top: 25px;
  }

  .project-address {
      font-family: "Open Sans";
      font-size: 16px;
      font-weight: 400;
      font-style: italic;
      line-height: 26px;
      color: #6d6d6f;
  }

  .project-link-map a {
      color: #fc0101;
      font-family: "Open Sans";
      font-size: 15px;
      font-style: italic;
      font-weight: 300;

      padding: 5px 34px 5px 0;

      background: transparent url('/assets/link_to_map.png') no-repeat right center;
  }

  .project-icons {
      margin-left: -5px;
      margin-top: 35px;
  }

  .project-icons img {
      margin-right: 10px;
  }

</style>

<div style="clear: both"></div>

<style>
  body {
      overflow-x: hidden;
  }

  .info-left {
      text-align: right;
      float: right;
      margin-top: 75px;
      margin-right: 40px;
  }

  .info-left .project-icons a {
      margin: 0 0 0 18px;
  }

  .info-left .hr-project-info {
      margin-left: 377px;
  }

  .project-section {
      width: 100%;
      height: 470px;
      overflow:hidden;

      margin: 0 auto;
  }

  .project-image {
    width: 50%;
    background-repeat: no-repeat;
    height: 470px;
  }

  .project-info {
      float: right;
      width: 50%;
      height: 470px;
      background-color: white;
      overflow: hidden;
  }
</style>

app/views/projects/layout.html.erb
<%
   active_menu_class('projects')
   page_title @project.title
%>

<div class="breadcrubms center960">
  <ul>
    <li><a href="/">Главная</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="/projects">Проекты</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="<%= project_path(@project.slug) %>"><%= @project.title %></a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li style="color: rgb(205, 205, 205);">Цены и планировки квартир</li>
    <li></li>
  </ul>
</div>

<div style="clear: both;"></div>
<hr class="hr-orange hr-breadcrubms">

<div class="objects">
  <section class="romanov-section">
    <div class="container">
      <div class="sixteen columns">
        <h1>Цены и планировки квартир</h1>
      </div>
      <div class="eleven columns">
        <hr class="hr-orange hr-objects-short">
        <div class="desc-p">
          <%= raw @project.layout %>
        </div>
      </div>
      <div class="four columns offset-by-one">
        <h2><%= @project.title %></h2>
        <hr class="hr-objects-menu">
        <%= render "objects_menu" %>
      </div>
    </div>
  </section>

  <% if @areas.present? %>
    <section class="description-section">
      <div class="container">
        <div class="sixteen columns">
          <h2 class="obj-decr-h2">Выберите тип квартиры</h2>
          <hr class="hr-orange hr-object-description">
          <div class="project-areas">
            <% if @areas.count > 3 %>
              <div class="arrows">
                <a class="right-arrow"></a>
                <a class="left-arrow"></a>
              </div>
            <% end %>
            <div class="areas desktop">
              <% @areas.each do |area| %>
                <%= render "area_view", area: area %>
              <% end %>
            </div>
            <div class="areas mobile">
              <% @areas.each do |area| %>
                <%= render "area_view", area: area %>
              <% end %>
            </div>
            <div class="pagination" style="display: block;"></div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </section>
  <% end %>

  <% if @layout.present? %>
    <div id="layout_description">
      <%= render "layout_description" %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<%
   active_menu_class('projects')
   page_title @project.title
%>

<div class="breadcrubms center960">
  <ul>
    <li><a href="/">Главная</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="/projects">Проекты</a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li><a href="<%= project_path(@project.slug) %>"><%= @project.title %></a></li>
    <li>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</li>
    <li style="color: rgb(205, 205, 205);">Описание объекта</li>
    <li></li>
  </ul>
</div>

<div style="clear: both;"></div>
<hr class="hr-orange hr-breadcrubms">

<div class="objects">
  <section class="romanov-section">
    <div class="container">
      <div class="eleven columns">
        <h1><%= @project.title %></h1>
        <h4 class="add-some-space"><%= @project.category %></h4>

        <hr class="hr-orange hr-objects-short">
        <p class="desc-p">
          <%= raw @project.description %>
        </p>
      </div>
      <%= render "side_menu" %>
    </div>
  </section>

  <section class="projects-slider show">
    <div class="project-slide"><div class="project-slide-zoom"></div></div>
    <div class="slider-thumbs center960">
      <% @project.photos.first(7).each_with_index do |photo, n| %>
          <a class="group1" href="<%= photo.file.url(:normal) %>">
          <% if n == 0 %>
              <%= image_tag photo.file.url(:thumb), class: 'thumb active-thumb' %>
          <% else %>
              <%= image_tag photo.file.url(:thumb), class: 'thumb' %>
          <% end %>
          </a>
      <% end %>
    </div>
  </section>

  <style>
    .active-thumb {
        border: 2px solid #fc0101;
    }

    .slider-thumbs {
        margin-top: 10px;
    }

    .slider-thumbs a { text-decoration: none; outline: none; }

    .slider-thumbs img {
        width: 107px;
        height: 67px;
        margin: 7px;
    }

    .active-thumb img {
        border: 2px solid orange;
        margin: 5px;
    }
  </style>

  <style>
      .map-section-projects {
          width: 100%;
          height: 355px;
      }
      #yamap {
          margin-top: 20px;
          width: 100%;
          height: 100%;
          position: relative;
      }

      a.yamap-link {
          position: absolute;
          bottom: 20px;
          left: 20px;
          z-index: 10;
          font-size: 14px;
          color: #fc2121;
      }
  </style>

  <script type="text/javascript">
    <% if @project.photos.first %>
    $('.project-slide').backstretch("<%= @project.photos.first.file.url %>");
    <% end %>

    $('.thumb').click(function() {
        $('.thumb img').removeClass('active-thumb');
        $(this).find('img').addClass('active-thumb');
        $('.project-slide .backstretch').remove();
        $('.project-slide').backstretch($(this).parent().attr('href'), {fade: 0});
    });
  </script>

  <section class="description-section">
    <div class="container">
      <div class="fifteen columns offset-by-one">
        <h2 class="obj-decr-h2">ОПИСАНИЕ ОБЪЕКТА</h2>
        <hr class="hr-orange hr-object-description">
        <%= raw @project.content %>
      </div>
    </div>
  </section>

  <section class="dislocation">
    <div class="container">
      <div class="eleven columns">
          <h2>РАСПОЛОЖЕНИЕ</h2>
          <hr class="hr-orange hr-object-description">
          <p><%= raw @project.location %></p>
      </div>
    </div>
  </section>

  <section class="map-section-projects">
    <a name="map"></a>
    <div id="yamap">
      <a class="yamap-link" href="http://maps.yandex.ru/?ll=<%= @project.lng %>,<%= @project.lat %>&z=16&l=map&p=<%= @project.lng %>,<%= @project.lat %>&oll=<%= @project.lng %>,<%= @project.lat %>&text=<%= @project.title %>" >
        Посмотреть на карте большего масштаба
      </a>
    </div>
  </section>

  <section class="dislocation-continued">
    <div class="container">
      <div class="fifteen columns offset-by-one clearfix">
        <%= raw @project.location_content %>

        <% if @project.objects.count > 0 %>
        <h4 class="dislocation-h4">Инфраструктура в шаговой доступности</h4>
        <ul class="object-icons">
          <% @project.objects.each do |o| %>
          <li class="object-icons-<%= o %>"><%= t(o, scope: 'objects')%></li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
  </section>
</div>

<script type="text/javascript">
  var projectSlider = new Slider;
  projectSlider.start()
    ymaps.ready(function () {
        var myMap = new ymaps.Map("yamap", {
                    center: [<%= @project.lat %>, <%= @project.lng %>],
                    zoom: 15
                }
        );

        myMap.controls.add('zoomControl', { left: 5, top: 5 });

        var myPlacemark2 = new ymaps.Placemark(
                [<%= @project.lat %>, <%= @project.lng %>],
                {
                    hintContent: '<%= @project.title %>'
                }, {
                    iconImageHref: '/assets/baloon.png',
                    iconImageSize: [96, 101],
                    iconImageOffset: [-60, -95]
                });
        myMap.geoObjects.add(myPlacemark2);
    });
</script>